version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: appointments_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: Appointments
    ports:
      - '3306:3306'
    volumes:
      - ./database:/docker-entrypoint-initdb.d
